[project]
name = "nada_data"
version = "0.1.0"
description = "Tabular data operations with nada_dsl"
authors = [
    {name = "Choose K"},
    {email = "team@choosek.com"}
]
dependencies = [
    "nada-dsl"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
